architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/reclaim.accesswidener")
}

repositories {
    maven { url = "https://api.modrinth.com/maven" }
}

dependencies {
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modImplementation("dev.architectury:architectury:${architectury_api_version}")
    modCompileOnly("maven.modrinth:forge-config-api-port:v${forge_config_api_port_version}-1.21.1-Fabric")
}

sourceSets.main {
    resources { // include generated resources in resources
        srcDir("src/generated/resources")
        exclude("src/generated/resources/.cache")
    }
}
