name: Build and Publish

on:
    push:
        branches:
            - 1.19/dev
            - 1.19/release

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Get branch name
                id: get_branch
                run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

            -   name: Get latest commit hash
                id: get_hash
                run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            -   name: Get MC version
                uses: christian-draeger/read-properties@908f99d3334be3802ec7cb528395a69d19914e7b
                id: read_properties
                with:
                    path: gradle.properties
                    properties: minecraft_version enabled_platforms mod_version archives_base_name

            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: 17
                    distribution: temurin

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2.4.2
                with:
                    gradle-version: 7.2

            -   name: Validate Gradle Wrapper
                uses: gradle/wrapper-validation-action@v1

            -   name: Grant execute permissions to gradlew
                run: chmod +x gradlew

            -   name: Create fabric_loader_dependencies.json
                run: |
                    mkdir -p fabric/run/config
                    echo '{
                      "version": 1,
                      "overrides": {
                        "forgeconfigapiport": {
                          "-depends": {
                            "com_electronwill_night-config_core": "*",
                            "com_electronwill_night-config_toml": "*"
                          }
                        }
                      }
                    }' > fabric/run/config/fabric_loader_dependencies.json

            -   name: Run Data Gen
                run: ./gradlew runDatagen --stacktrace --no-daemon

            -   name: Build
                run: ./gradlew build

            -   name: Send building message to discord
                if: github.event_name == 'push' && github.repository_id == '634260349'
                uses: realRobotix/action-discord-notifier@release-master
                with:
                    webhook: ${{ secrets.DISCORD_WEBHOOK }}
                    message-title: Building mod from branch ${{ steps.get_branch.outputs.branch }}

            -   name: Remove extra JARs
                run: |
                    rm fabric/build/libs/*-dev-shadow.jar
                    rm fabric/build/libs/*-sources.jar
                    rm forge/build/libs/*-dev-shadow.jar
                    rm forge/build/libs/*-sources.jar

            -   name: Rename Jars
                run: |
                    mv fabric/build/libs/*.jar fabric/build/libs/${{ steps.read_properties.outputs.archives_base_name }}-${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}-fabric-nightly-${{ steps.get_hash.outputs.sha_short }}.jar
                    mv forge/build/libs/*.jar forge/build/libs/${{ steps.read_properties.outputs.archives_base_name }}-${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}-forge-nightly-${{ steps.get_hash.outputs.sha_short }}.jar

            -   name: Send built file to discord
                if: github.event_name == 'push' && github.repository_id == '634260349'
                uses: sinshutu/upload-to-discord@master
                env:
                    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
                with:
                    args: ./forge/build/libs/${{ steps.read_properties.outputs.archives_base_name }}-${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}-forge-nightly-${{ steps.get_hash.outputs.sha_short }}.jar ./fabric/build/libs/${{ steps.read_properties.outputs.archives_base_name }}-${{ steps.read_properties.outputs.minecraft_version }}-${{ steps.read_properties.outputs.mod_version }}-fabric-nightly-${{ steps.get_hash.outputs.sha_short }}.jar
